import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import all from '../public/sample/all.json'
import d30 from '../public/sample/30d.json'
import d7 from '../public/sample/7d.json'
import today from '../public/sample/today.json'
import { selectSeries, wallCells, todayISO } from './grid'
import type { SummaryPayload } from './types'

// The committed demo payloads are generated by scripts/gendemo and must stay
// loadable by the real dashboard selectors. Cast like api.ts does at the
// fetch boundary; the runtime assertions below are the real schema guard.
const payloads: Record<string, SummaryPayload> = {
  all: all as SummaryPayload,
  today: today as SummaryPayload,
  '7d': d7 as SummaryPayload,
  '30d': d30 as SummaryPayload,
}

describe('committed demo sample payloads', () => {
  it('every period has live totals, sources and calendar days', () => {
    for (const [name, p] of Object.entries(payloads)) {
      expect(p.all.total, name).toBeGreaterThan(0)
      expect(p.by_source.length, name).toBeGreaterThanOrEqual(4)
      expect(p.errors, name).toEqual([])
      expect(p.scanned_at, name).toBeTruthy()
      expect(selectSeries(p, { kind: 'all', id: '' }).days.length, name).toBeGreaterThan(0)
      expect(wallCells(p, { kind: 'all', id: '' }, todayISO()).length, name).toBeGreaterThan(0)
    }
  })

  it('community is present but unconfigured, never a fake rank', () => {
    for (const [name, p] of Object.entries(payloads)) {
      expect(p.community?.enabled, name).toBe(false)
      expect(p.community?.today.status, name).toBe('service_unconfigured')
    }
  })

  it('every period carries an evaluation computed by the real evaluator', () => {
    const levels = new Set([
      'none',
      'insufficient',
      'high_cost',
      'high_usage',
      'multi_model',
      'single_model',
      'cache_reuse',
      'steady',
      'light',
    ])
    for (const [name, p] of Object.entries(payloads)) {
      expect(p.evaluation, name).toBeTruthy()
      expect(levels.has(p.evaluation?.level ?? ''), name).toBe(true)
      expect(p.evaluation?.summary, name).toBeTruthy()
      expect(p.evaluation?.reason, name).toBeTruthy()
    }
    // The synthetic ledger is a heavy multi-vendor one; the flagship
    // all-period page must profile it as such, not as a hardcoded string.
    expect(payloads.all.evaluation?.level).toBe('high_usage')
    expect(payloads.all.evaluation?.summary).toBe('高强度使用')
  })

  it('today lands on the sample calendar date', () => {
    // Samples are committed artifacts regenerated at build time: their
    // "today" is the payload's own scanned_at day, not the wall clock —
    // asserting wall-clock today would fail one day after generation.
    const days = selectSeries(payloads.today, { kind: 'all', id: '' }).days
    const sampleDay = (payloads.today.scanned_at ?? '').slice(0, 10)
    expect(sampleDay).toMatch(/^\d{4}-\d{2}-\d{2}$/)
    expect(days.some((d) => d.date === sampleDay && d.total > 0)).toBe(true)
  })

  it('gendemo pins the demo portrait seed', () => {
    const SRC = dirname(fileURLToPath(import.meta.url))
    const src = readFileSync(join(SRC, '..', '..', 'scripts', 'gendemo', 'main.go'), 'utf8')
    expect(src).toContain('PortraitSeed')
    expect(src).toContain('"demo-v1"')
  })

  it('every period carries a demo-seeded portrait and a model breakdown', () => {
    for (const [name, p] of Object.entries(payloads)) {
      expect(p.portrait?.state, name).toBe('ok')
      expect(p.portrait?.primary, name).toBeTruthy()
      expect(p.portrait?.primary, name).not.toBe('—')
      expect(p.portrait?.primary, name).not.toBe('数据不足')
      expect(p.portrait?.detail, name).toContain('tokens')
      expect(p.portrait?.tags?.length ?? 0, name).toBeLessThanOrEqual(2)
      expect(p.by_model?.length, name).toBeGreaterThan(0)
      for (const m of p.by_model ?? []) {
        expect(m.vendor, name).toBeTruthy()
        expect(m.unit_prices, name).toBeTruthy()
        expect(m.total_m, name).toBeTruthy()
      }
    }
  })

  it('exposes today totals and never a rank insight line', () => {
    for (const [name, p] of Object.entries(payloads)) {
      expect(typeof p.calendar?.all.stats.today_total, name).toBe('number')
      expect(p.calendar?.all.stats.today_total_m, name).toBeTruthy()
      for (const line of p.insights ?? []) {
        expect(line.kind, name).not.toBe('community')
        expect(line.text, name).not.toContain('社区排名')
      }
    }
    // The today window is exactly today's bucket.
    expect(payloads.today.calendar?.all.stats.today_total).toBe(payloads.today.all.total)
  })
})
