import { describe, expect, it } from 'vitest'
import all from '../public/sample/all.json'
import d30 from '../public/sample/30d.json'
import d7 from '../public/sample/7d.json'
import today from '../public/sample/today.json'
import { selectSeries, wallCells, todayISO } from './grid'
import type { SummaryPayload } from './types'

// The committed demo payloads are generated by scripts/gendemo and must stay
// loadable by the real dashboard selectors. Cast like api.ts does at the
// fetch boundary; the runtime assertions below are the real schema guard.
const payloads: Record<string, SummaryPayload> = {
  all: all as SummaryPayload,
  today: today as SummaryPayload,
  '7d': d7 as SummaryPayload,
  '30d': d30 as SummaryPayload,
}

describe('committed demo sample payloads', () => {
  it('every period has live totals, sources and calendar days', () => {
    for (const [name, p] of Object.entries(payloads)) {
      expect(p.all.total, name).toBeGreaterThan(0)
      expect(p.by_source.length, name).toBeGreaterThanOrEqual(4)
      expect(p.errors, name).toEqual([])
      expect(p.scanned_at, name).toBeTruthy()
      expect(selectSeries(p, { kind: 'all', id: '' }).days.length, name).toBeGreaterThan(0)
      expect(wallCells(p, { kind: 'all', id: '' }, todayISO()).length, name).toBeGreaterThan(0)
    }
  })

  it('community is present but unconfigured, never a fake rank', () => {
    for (const [name, p] of Object.entries(payloads)) {
      expect(p.community?.enabled, name).toBe(false)
      expect(p.community?.today.status, name).toBe('service_unconfigured')
    }
  })

  it('today lands on the real calendar date', () => {
    const days = selectSeries(payloads.today, { kind: 'all', id: '' }).days
    expect(days.some((d) => d.date === todayISO() && d.total > 0)).toBe(true)
  })
})
